### ISSUE TITLE
Missionchanges

### ISSUE THREAD

**Issue by Suchty112** [tobst96/mission-chief-bot-jsons#6]
Auch wenn es noch nicht offiziell ist, es gab an bereits vorhandenen missionen einige änderungen, die glaube ich auch zu änderungen an den jsons führen.

Kleiner Waldbrand (015)
- 1010 Credits zu 1210 Credits
- 800 l zu 1200 l

Großer Waldbrand (134 ohne Pol)
- 4000 Credits zu 5000 oder 6000 Credits (müsstest du in der hilfe nachgucken)
- 8000 l zu 10000 l
- 18x Person FW zu 27x Personal FW

Großer Waldbrand (135 mit Pol)
- 4100 Credits zu 5100 oder 6100 Credits (müsstest du in der hilfe nachgucken)
- 8500 l zu 10500 l
- 18x Person FW zu 27x Person FW

Großfeuer im Wald (136 ohne Pol)
- 8000 Credits zu 10000 Credits
- 25000 l zu 50000 l
- 80x Person FW zu 90x Personal FW

Großfeuer im Wald (137 mit Pol)
- 8100 Credits zu 10100 Credits
- 25000 l zu 50000 l
- 80x Person FW zu 90x Personal FW

Brennende Waldhütte (441)
- 1600 Credits zu 1900 Credits
- 4000 l zu 5000 l
- 10x Person FW zu 18x Personal FW

**Comment by tobst96** [comment]
Ist nun im Pull requets:
https://github.com/jackbayliss/mission-chief-bot-jsons/pull/75
