### ISSUE TITLE
521 Explosion in Feuerwerksfabrik

### ISSUE THREAD

**Issue by Suchty112** [tobst96/mission-chief-bot-jsons#7]
https://github.com/tobst96/mission-chief-bot-jsons/blob/main/missions/de/521.json
https://www.leitstellenspiel.de/einsaetze/521
in der json fehlt der LKW K 9 + BRmG R . 
Musste ich grad nachalarmieren

**Comment by Suchty112** [comment]
https://github.com/tobst96/mission-chief-bot-jsons/blob/main/missions/de/348.json
https://www.leitstellenspiel.de/einsaetze/348
fehlt genau das gleiche wie oben

**Comment by Suchty112** [comment]
https://github.com/tobst96/mission-chief-bot-jsons/blob/main/missions/de/622.json
Wieso zur hölle 4rtw und 4 nef? xD
https://www.leitstellenspiel.de/einsaetze/622
das ist nur ein Allergischer Schock mit 1 RTW und 80% NEF Chance xD

**Comment by tobst96** [comment]
https://github.com/jackbayliss/mission-chief-bot-jsons/pull/81
