### ISSUE TITLE
ID 93 Brennender Bus

### ISSUE THREAD

**Issue by Suchty112** [tobst96/mission-chief-bot-jsons#8]
https://github.com/tobst96/mission-chief-bot-jsons/blob/main/missions/de/93.json
Wenn ich das richtig sehe fehlt 1 LF und 3 fustw
https://www.leitstellenspiel.de/einsaetze/93

**Comment by tobst96** [comment]
Es wird auf 6xLF 2xELW1 und 5xStreifenwagen geändert.

**Comment by tobst96** [comment]
Kommt mit dem nächsten Update Online
